project:
  type: default
  output-dir: docs
  render:
    - w05-fund-contract.qmd
    - w06-venture-contract.qmd

lang: zh-CN

format:
  html:
    theme: cosmo
    css: pevc-handout.css
    toc: true
    toc-title: "本讲目录"
    toc-location: left
    toc-depth: 3
    number-sections: true
    smooth-scroll: true
    anchor-sections: true
    link-external-newwindow: true
    embed-resources: true
    self-contained-math: true
    html-math-method: katex
